permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  include_device_information: true
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyS0
  adapter: deconz
frontend:
  port: 8080
  host: 0.0.0.0
availability: true
homeassistant: true